-- FDA 승인 데이터 테이블
CREATE TABLE IF NOT EXISTS fda_approvals (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  approval_month TEXT,
  approval_date TEXT,
  nda_bla_number TEXT,
  application_number REAL,
  application_type TEXT,
  product_name TEXT,
  active_ingredient TEXT,
  sponsor TEXT,
  indication TEXT,
  therapeutic_area TEXT,
  is_oncology TEXT,
  is_biosimilar TEXT,
  is_novel TEXT,
  is_orphan TEXT,
  approval_type TEXT,
  remarks TEXT,
  fda_approval_page TEXT,
  fda_drugs_url TEXT,
  approval_letter TEXT,
  source TEXT,
  data_collection_date TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_approval_date ON fda_approvals(approval_date);
CREATE INDEX IF NOT EXISTS idx_therapeutic_area ON fda_approvals(therapeutic_area);
CREATE INDEX IF NOT EXISTS idx_sponsor ON fda_approvals(sponsor);
CREATE INDEX IF NOT EXISTS idx_is_oncology ON fda_approvals(is_oncology);
CREATE INDEX IF NOT EXISTS idx_is_novel ON fda_approvals(is_novel);
CREATE INDEX IF NOT EXISTS idx_is_biosimilar ON fda_approvals(is_biosimilar);
CREATE INDEX IF NOT EXISTS idx_approval_month ON fda_approvals(approval_month);

-- 데이터 임포트
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-20', 'NDA022211', 22211.0, 'NDA', 'ZIRGAN', 'GANCICLOVIR', 'BAUSCH AND LOMB', 'Treatment of cytomegalovirus (CMV) retinitis in immunocompromised patients', 'Cytomegalovirus Nucleoside Analog DNA Polymerase Inhibitor', 'N', 'N', 'N', 'Y', '정규승인', '변경승인. 희귀의약품. DNA Polymerase Inhibitors', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=022211', 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/022211Orig1s007ltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-16', 'BLA761269', 761269.0, 'BLA', 'LEQEMBI', 'LECANEMAB', 'EISAI INC', 'Treatment of Alzheimer''s disease in adults with mild cognitive impairment or mild dementia stage of disease', 'Amyloid Beta-directed Antibody', 'N', 'N', 'N', 'N', '정규승인', '변경승인. Amyloid Beta-directed Antibody Interactions', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=761269', 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/761269Orig1s011ltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-13', 'BLA761274', 761274.0, 'BLA', 'Unknown', NULL, 'BIOCON BIOLOGICS INC', 'Consult FDA-approved labeling for complete indication and usage information', 'Not specified', 'N', 'N', 'N', 'N', '정규승인', '변경승인', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=761274', 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/761274Orig1s001ltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-16', 'NDA212849', 212849.0, 'NDA', 'RYKINDO EXTENDED-RELEASE MICROSPHERES', 'RISPERIDONE', 'SHANDONG LUYE', 'Consult FDA-approved labeling for complete indication and usage information', 'Not specified', 'N', 'N', 'N', 'N', '정규승인', '변경승인', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=212849', 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/212849Orig1s003Correctedltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-14', 'NDA021812', 21812.0, 'NDA', 'WOMENS ROGAINE UNSCENTED', 'MINOXIDIL', 'KENVUE BRANDS', 'Topical treatment of androgenetic alopecia (male and female pattern baldness)', 'Arteriolar Vasodilator', 'N', 'N', 'N', 'N', '정규승인', '변경승인', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=021812', 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/019501Orig1s036,020834Orig1s021,021812Orig1s020ltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-14', 'NDA019501', 19501.0, 'NDA', 'WOMENS ROGAINE UNSCENTED', 'MINOXIDIL', 'KENVUE BRANDS', 'Topical treatment of androgenetic alopecia (male and female pattern baldness)', 'Arteriolar Vasodilator', 'N', 'N', 'N', 'N', '정규승인', '변경승인', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=019501', 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/019501Orig1s036,020834Orig1s021,021812Orig1s020ltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-15', 'BLA761379', 761379.0, 'BLA', 'OTULFI', 'USTEKINUMAB', 'FRESENIUS KABI USA', 'Treatment of moderate to severe plaque psoriasis in adult patients who are candidates for systemic therapy or phototherapy', 'Interleukin-12 Antagonist', 'N', 'Y', 'N', 'N', '정규승인', '변경승인. Interleukin-12 Antagonists', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=761379', 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/761379Orig1s009ltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-07', 'BLA761406', 761406.0, 'BLA', 'YESINTEK', 'USTEKINUMAB', 'BIOCON BIOLOGICS INC', 'Treatment of moderate to severe plaque psoriasis in adult patients who are candidates for systemic therapy or phototherapy', 'Interleukin-12 Antagonist', 'N', 'Y', 'N', 'N', '정규승인', '변경승인. Interleukin-12 Antagonists', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=761406', NULL, 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-14', 'BLA761420', 761420.0, 'BLA', 'AVTOZMA', 'TOCILIZUMAB', 'CELLTRION INC', 'Treatment of adult patients with moderately to severely active rheumatoid arthritis', 'Interleukin-6 Receptor Antagonist', 'N', 'Y', 'N', 'N', '정규승인', '변경승인. Interleukin 6 Receptor Antagonists', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=761420', 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/761420Orig1s005ltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-15', 'BLA761027', 761027.0, 'BLA', 'Unknown', NULL, 'ACCORD BIOPHARMA INC.', 'Consult FDA-approved labeling for complete indication and usage information', 'Not specified', 'N', 'N', 'N', 'N', '정규승인', NULL, NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=761027', 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/761027Orig1s000ltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-16', 'NDA021529', 21529.0, 'NDA', 'NEXPLANON', 'ETONOGESTREL', 'ORGANON', 'Prevention of pregnancy in women of reproductive potential', 'Progestin', 'N', 'N', 'N', 'N', '정규승인', '변경승인', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=021529', 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/021529Orig1s027ltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-20', 'NDA215866', 215866.0, 'NDA', 'MOUNJARO', 'TIRZEPATIDE', 'ELI LILLY AND CO', 'Adjunct to diet and exercise to improve glycemic control in adults with type 2 diabetes mellitus', 'Glucose-dependent Insulinotropic Polypeptide Receptor Agonist', 'N', 'N', 'N', 'N', '정규승인', '변경승인. G-Protein-linked Receptor Interactions', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=215866', 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/215866Orig1s009ltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-15', 'NDA021920', 21920.0, 'NDA', 'NAPROXEN SODIUM', 'NAPROXEN SODIUM', 'BIONPHARMA', 'Consult FDA-approved labeling for complete indication and usage information', 'Not specified', 'N', 'N', 'N', 'N', '정규승인', '변경승인', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=021920', 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/021920Orig1s041ltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-09', 'NDA208411', 208411.0, 'NDA', 'NARCAN', 'NALOXONE HYDROCHLORIDE', 'EMERGENT', 'Consult FDA-approved labeling for complete indication and usage information', 'Not specified', 'N', 'N', 'N', 'N', '정규승인', '변경승인', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=208411', 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/208411Orig1s010ltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-13', 'NDA018735', 18735.0, 'NDA', 'ISOVUE 200', 'IOPAMIDOL', 'BRACCO', 'For use in diagnostic imaging procedures to enhance visualization of internal structures', 'Radiographic Contrast Agent', 'N', 'N', 'N', 'N', '정규승인', '변경승인. X-Ray Contrast Activity', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=018735', 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/018735Orig1s074;020327Orig1s028ltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-15', 'NDA216774', 216774.0, 'NDA', 'ALVAIZ', 'ELTROMBOPAG CHOLINE', 'TEVA PHARMS INC', 'Consult FDA-approved labeling for complete indication and usage information', 'Not specified', 'N', 'N', 'N', 'N', '정규승인', '변경승인', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=216774', 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/216774Orig1s006ltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-21', 'BLA761498', 761498.0, 'BLA', 'Unknown', NULL, 'CELLTRION INC', 'Consult FDA-approved labeling for complete indication and usage information', 'Not specified', 'N', 'N', 'N', 'N', '정규승인', NULL, NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=761498', 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/761498Orig1s000ltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-21', 'NDA219285', 219285.0, 'NDA', 'EVRYSDI', 'RISDIPLAM', 'GENENTECH INC', 'Treatment of spinal muscular atrophy (SMA) in pediatric and adult patients', 'Survival of Motor Neuron 2 Splicing Modifier', 'N', 'N', 'N', 'N', '정규승인', '변경승인. Survival of Motor Neuron 2 Splicing Modifiers', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=219285', 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/219285Orig1s001,213535Orig1s016ltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-08', 'NDA218171', 218171.0, 'NDA', 'ENSACOVE', 'ENSARTINIB HYDROCHLORIDE', 'XCOVERY', 'Consult FDA-approved labeling for complete indication and usage information', 'Not specified', 'N', 'N', 'N', 'N', '정규승인', '변경승인', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=218171', 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/218171Orig1s002ltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-14', 'NDA021588', 21588.0, 'NDA', 'GLEEVEC', 'IMATINIB MESYLATE', 'NOVARTIS', 'Consult FDA-approved labeling for complete indication and usage information', 'Not specified', 'N', 'N', 'N', 'Y', '정규승인', '변경승인. 희귀의약품', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=021588', 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/021588Orig1s065ltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-13', 'NDA020327', 20327.0, 'NDA', 'ISOVUE 300', 'IOPAMIDOL', 'BRACCO', 'For use in diagnostic imaging procedures to enhance visualization of internal structures', 'Radiographic Contrast Agent', 'N', 'N', 'N', 'N', '정규승인', '변경승인. X-Ray Contrast Activity', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=020327', 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/018735Orig1s074;020327Orig1s028ltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-12', 'NDA211241', 211241.0, 'NDA', 'ZYCUBO', 'COPPER HISTIDINATE', 'SENTYNL THERAPS INC', 'Treatment of copper deficiency in patients with Menkes disease, a rare genetic disorder of copper metabolism', 'Not specified', 'N', 'N', 'Y', 'Y', '신속승인', '신규 분자 실체 (NME). 희귀의약품', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=211241', 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/211241Orig1s000ltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-12', 'BLA020367', 20367.0, 'BLA', 'CEREZYME', 'IMIGLUCERASE', 'GENZYME', 'Enzyme replacement therapy for specific lysosomal storage disorders', 'Hydrolytic Lysosomal Glucocerebroside-specific Enzyme', 'N', 'N', 'N', 'Y', '정규승인', '변경승인. 희귀의약품', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=020367', 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/020367Orig1s123ltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-06', 'NDA213026', 213026.0, 'NDA', 'AMONDYS 45', 'CASIMERSEN', 'SAREPTA THERAPS INC', 'Consult FDA-approved labeling for complete indication and usage information', 'Antisense Oligonucleotide', 'N', 'N', 'N', 'Y', '정규승인', '변경승인. 희귀의약품', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=213026', 'http://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/213026Orig1s016ltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-09', 'NDA211616', 211616.0, 'NDA', 'NEXLETOL', 'BEMPEDOIC ACID', 'ESPERION THERAPS INC', 'Consult FDA-approved labeling for complete indication and usage information', 'Adenosine Triphosphate-Citrate Lyase Inhibitor', 'N', 'N', 'N', 'N', '정규승인', '변경승인. Adenosine Triphosphate-Citrate Lyase Inhibitors', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=211616', 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/211616Orig1s026ltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-09', 'NDA211617', 211617.0, 'NDA', 'NEXLIZET', 'BEMPEDOIC ACID', 'ESPERION THERAPS INC', 'Consult FDA-approved labeling for complete indication and usage information', 'Adenosine Triphosphate-Citrate Lyase Inhibitor', 'N', 'N', 'N', 'N', '정규승인', '변경승인. Adenosine Triphosphate-Citrate Lyase Inhibitors', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=211617', 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/211617Orig1s031ltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-14', 'NDA020834', 20834.0, 'NDA', 'MENS ROGAINE EXTRA STRENGTH UNSCENTED', 'MINOXIDIL', 'KENVUE BRANDS', 'Topical treatment of androgenetic alopecia (male and female pattern baldness)', 'Arteriolar Vasodilator', 'N', 'N', 'N', 'N', '정규승인', '변경승인', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=020834', 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/019501Orig1s036,020834Orig1s021,021812Orig1s020ltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-17', 'NDA019708', 19708.0, 'NDA', 'POTASSIUM CHLORIDE IN SODIUM CHLORIDE', 'POTASSIUM CHLORIDE', 'B BRAUN', 'Consult FDA-approved labeling for complete indication and usage information', 'Not specified', 'N', 'N', 'N', 'N', '정규승인', '변경승인', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=019708', 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/019708Orig1s040ltr.pdf', 'FDA Official', '2026-01-26');
INSERT INTO fda_approvals (approval_month, approval_date, nda_bla_number, application_number, application_type, product_name, active_ingredient, sponsor, indication, therapeutic_area, is_oncology, is_biosimilar, is_novel, is_orphan, approval_type, remarks, fda_approval_page, fda_drugs_url, approval_letter, source, data_collection_date) VALUES ('2026-01', '2026-01-20', 'NDA217806', 217806.0, 'NDA', 'ZEPBOUND', 'TIRZEPATIDE', 'ELI LILLY AND CO', 'Adjunct to diet and exercise to improve glycemic control in adults with type 2 diabetes mellitus', 'Glucose-dependent Insulinotropic Polypeptide Receptor Agonist', 'N', 'N', 'N', 'N', '정규승인', '변경승인. G-Protein-linked Receptor Interactions', NULL, 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&ApplNo=217806', 'https://www.accessdata.fda.gov/drugsatfda_docs/appletter/2026/217806Orig1s002ltr.pdf', 'FDA Official', '2026-01-26');